version: '3'

services:
  db:
    image: mongo
    container_name: db
    restart: always
    ports:
      - 27017:27017
    networks:
      - app_network
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    restart: always
    ports:
      - 3000:80
    networks:
      - app_network
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    restart: always
    ports:
      - 8080:8080
    networks:
      - app_network

networks:
  app_network:
    external: true
